### ISSUE TITLE
Error during docker-compose phase

### ISSUE THREAD

**Issue by rafaferreira** [8x8Cloud/logstash-in-a-box#10]
Hi Greg,

I'm trying to start the container in my box (Mac) and I'm receiving, an error:

```
$ docker-compose -f docker-compose.yml up -d
Creating network "logfiles_esnet" with driver "bridge"
Creating volume "logfiles_esdata2" with local driver
Creating volume "logfiles_esdata1" with local driver
Pulling elasticsearch-master (docker.elastic.co/elasticsearch/elasticsearch:5.2.1)...
Pulling repository docker.elastic.co/elasticsearch/elasticsearch
ERROR: Error: image elasticsearch/elasticsearch:5.2.1 not found
```

I tried with **5.2.2** that seems to be the latest one (February 28, 2017) and did not work as well.

**Update:**
I'll try latter, I think should be related to Amazon outage as docker.elastic.co seems to be off too.

http://www.theverge.com/2017/2/28/14765042/amazon-s3-outage-causing-trouble

**Comment by rafaferreira** [comment]
Now Amazon is back, seems to be working. I'll go ahead with 5.2.2 and let you know.

**Comment by rafaferreira** [comment]
The installation seems to be good, all containers up, but when I fire my browser I see many redirects and nothing shows up.

**Comment by kog** [comment]
@rafaferreira - hey, sorry for the slow response, been busy in late night design reviews at the office. I'll try and drop by your desk, but can you please add the output of both `docker info` and `docker version` to the thread?

EDIT: it would also be good to know how many processors/how much RAM you gave to the Docker host. The default behavior of 2GB of RAM isn't enough for the ES instances to run.

**Comment by kog** [comment]
Looking over this the other day with @rafaferreira in person, it seems like part of the problem was indeed resolved by giving Docker 8GB of ram. Another part of the problem was that it wasn't readily obvious that there's a filename pattern being scanned for (*request.log*), and once we changed the filename it looks like stuff started to get indexed.

There may still be other problems, so I'll work through them the next time @rafaferreira is available.

**Comment by kog** [comment]
I'm going to go ahead and close this since there's been no update. Feel free to re-open if there are any updates.
